apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  namespace: ml-training
  labels:
    app: training-job
    project: mlops-pytorch-pipeline
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: training-job
        project: mlops-pytorch-pipeline
    spec:
      restartPolicy: Never
      containers:
        - name: train
          image: mlops-train:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: OMP_NUM_THREADS
              value: "2"
            - name: MKL_NUM_THREADS
              value: "2"
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - name: training-config
              mountPath: /app/configs
            - name: data
              mountPath: /app/data
            - name: checkpoints
              mountPath: /app/checkpoints
      volumes:
        - name: training-config
          configMap:
            name: training-config
        - name: data
          persistentVolumeClaim:
            claimName: training-data-pvc
        - name: checkpoints
          persistentVolumeClaim:
            claimName: training-checkpoints-pvc
